### PR TITLE
feat(facade) Adds a customized function. addFunction(string $name, \Closure $func)

### PR DESCRIPTION
**Pull request by Tinywan**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@techoner @basakest plz review

**Comment by leeqvip** [comment]
@Tinywan  Please modify the comment message, format reference: [Angular Commit Message Conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format);

**Comment by Tinywan** [comment]
@techoner It has been modified

**Pull request merged**
